#!/bin/sh
# Authors: Vitaly Lipatov <lav@etersoft.ru>
#          Konstantin Baev <kipruss@altlinux.org>
#          Pavel Shilovsky <piastry@etersoft.ru>
# 2006, 2007, 2008, 2009, 2010, 2013 Public domain

cd @DATADIR@
sh buildmodule.sh
